### ISSUE TITLE
issues on MacOS Monterey

### ISSUE THREAD

**Issue by Nyryzu** [balopez83/Surface_Pro_3_Hackintosh#10]
I am on the latest EFI update and MacOS Monterey(updated from BigSur)
 I tweaked the pmset values like you instructed in the quirks and fixes section of the guide. 
NB: I want to say thank you so much for your amazing work to bring life back into my old Surface pro 3 and I hope you can enable hackintoshing on newer Surfaces as well.

Anyway here are my little issues as of now:

- Clicking on sleep turns off the screen momentarily and then it turns back on and 
when I make it sleep using the lid (it works after a warm boot) it shuts off completely after a few minutes which is very annoying and unproductive.

- Fan is on most of the time without any significant load going on (it was much quieter on BigSur)

 - Also Firefox crashes a lot, it was working perfectly before the update
 
 *Everything else works fine

Thank you for your work once again.

**Comment by balopez83** [comment]
@Nyryzu This issue seems odd and not exactly sure why its not working but maybe I can offer a few things to try so we can figure it out. 

First thing I need to know though is the following:

- What version of the Surface Pro 3 are you using? (i3, i5, i7?)

As for some possible reasons for the issues:

1. I suspect the first issue might be related to the wonky way macOS does sleep and because it's technically incompatible with the SP3. For the Surface Pro 3 Sleep is only enabled as Hibernate and it takes a good 20 seconds to fully go to sleep. If you touch the screen, keyboard, trackpad, etc. while it is going to sleep you can inadvertently kick it out of sleep. Once it does go to sleep it will only wake with the power button. If you try to go to sleep by closing the keyboard, it won't work properly and it will wake up and leave the screen on. 
If you don't have it can you download/run Hackintool? Click on the "Power" tab and make sure that Hibernate mode says 25. Its possible that didn't take and could be your issue assuming you're also on EFI version 5.0.0. If it does say 25, can you run this command  from terminal: `sudo pmset -a hibernatemode 0;` and then run `sudo pmset -a hibernatemode 25;` again. Reboot and try to sleep the computer again and let me know if that fixes your issue. I have noticed that macOS can get a corrupted hibernation file preventing sleep and switching the sleep modes like this usually resolves the corrupt hibernation file issue.
3. I would expect the Fan to be on more after upgrading to Monterey. The OS is re-indexing everything for spotlight and that can take some time for that to complete. Monterey is also kinda buggy for some reason on the SP3, even having Volume Hash Mismatch errors that can cause some annoying bugs in the OS that cannot really be resolved as far as I know. Its not detrimental but annoying. If the fan doesn't settle down in a day or two then something else may be wrong. Each OS including Ventura, increases its 3D graphics demands as well so it is a lot of work for the old SP3's to handle. I am working on a major refactor of the EFI currently that seems very stable on Monterey and I hope to release it soon which might resolve some things for you. 
4. I haven't tried Firefox yet but will and will let you know if I see any issues.

**Comment by Nyryzu** [comment]
My Surface is the Pro 3 I7 model

Anyway here is a screenshot of the Hackintool
Perhaps you can spot something weird in my values

![Screenshot 2023-05-14 at 7 10 56 PM](https://github.com/balopez83/Surface_Pro_3_Hackintosh/assets/57531374/1b539473-1400-4737-869b-7a7adefa8851)

**Comment by balopez83** [comment]
@Nyryzu Those values look fine. Try that option of switching back to hibernatemode 0 and then back to 25 as mentioned above and let me know how it goes.

Since you have the i7 model can you also let me know if you have any graphics glitches? It was an issue on previous versions of my EFI on i7 SP3's so curious if you're having those issues? I am trying to resolve them but don't have an i7 to test on. You can test 3d graphics glitches/artifacts by running any 3d app or multiple apps. See issue #9 for examples.

Let me know if your hibernation/sleep works better after changing the hibernatemode value.

**Comment by Nyryzu** [comment]
I tried putting the value at 0 and then 25 and restarted but nthg really changed. 
Perhaps I should delete some kexts I added myself and then see if it fixes the issues.
Regarding graphical glitching, there is none so far. Its all good, even though I notice that stuff like pulling the right side window or accessing the control center is a bit laggy, I noticed that some animations are really smooth and fast and some are laggy at first then it gets a bit better. 
Anything else you want to test out just let me know I will be happy to help!

**Comment by balopez83** [comment]
@Nyryzu Yeah if you can try a clean EFI and see if that resolves it. Only change your smbios information if you added it so it doesn't break your iServices if you're using them. Careful with whatever you use to edit the config as well. ProperTree and Xcode is fine but OC configurator can be risky if you don't use a version for that specific version of OpenCore. If you want to wait I should have a new release later today if all goes well. It's a really big overhaul and so while it doesn't really add many features it should make things a little more reliable.

The lag you experience with the graphics makes sense due to the limited amount of dedicated memory and the age and limitations of these old graphics. I'm glad it's not glitching so hope I finally fixed the i7 graphics issues. It's possible the next release might make graphics a little smoother for you but unsure.

**Comment by Nyryzu** [comment]
That's awesome! Don't rush the release it's alright. It's already night time where I live so I will be back to fixing my SP3 tomorrow. Good luck and have a good day

**Comment by balopez83** [comment]
@Nyryzu I just released a version 5.1.0 which hopefully will work a little more reliably. Let me know if you have any issues and also let me know if you get any screen glitches with this release too.

**Comment by Nyryzu** [comment]
Hello, I couldn't copy the new EFI release to my EFI partition because its telling me that it's full, but the thing is, i deleted everything and still the space won't clear out! 
Any tips on why this is happening?

**Comment by balopez83** [comment]
@Nyryzu Saw an email of a comment about the storage on the EFI partition but don't see it here; assuming you deleted it. If you didn't figure it out yet, I think macOS is holding the files in the trash and emptying it should resolve it. 

I tried Firefox and while mine isn't crashing like yours, it is painfully slow for some reason. I will see if I can figure it out but perhaps there is some sort of acceleration compatibility issue. I think Chrome and Edge work as expected so not sure why Firefox is running so badly. 

Let me know if sleep/hibernation is working now.

**Comment by Nyryzu** [comment]
Thanks for the new release! Yes I solved the full space issue by emptying the bin itself lol

Here are my remarks so far

- I noticed small improvements in the UI animation speed

- Firefox is magically fixed! Not sure how but its working properly now (I should note that the new release did not fix it right away but something else might have did) so it could still be a problem for others

- Sleep is still problematic, pressing the sleep menu button doesn't always put computer in sleep mode and when it does, it shuts off completely/hibernate so as a result sleep function is non existent as of yet

**Comment by balopez83** [comment]
@Nyryzu Glad to hear everything is working better!

I suspect the Firefox issue is related to graphics acceleration but not sure. I think I am going to have to split out the config files for the i7 model as that might be part of the issue. Currently I am using one that fixes the i7 graphics issues but I suspect may be causing some for the i3 & i7 models. I believe I figured out the problems originally causing glitches for all models and will release those fixes soon.

You "sleep" is now actually working correctly unfortunately. I say unfortunately because the Surface devices have the worst sleep support with macOS. Basically due to the instant on features that Microsoft put into it they didn't think anyone would actually want or need to use standard sleep. Because the hardware isn't capable of it and macOS doesn't know how to handle modern standby, the only method to get "sleep" to work without having the computer stay awake with the fan on and only the screen off was to force macOS to use the very old hibernation function. The result is the full shutdown of macOS with a "resume" functionality once it powers back up. Not ideal but the only current way to make it work.

I am still trying to find another way around it to get it working better but so far this is the best we can get. 

Previously if you selected sleep the screen would turn off and everything else would keep running using battery only a little slower than when the screen was on. Additionally, it was very unreliable at "resuming" often needing to be forcefully shut down.

Keep in mind that to "hibernate" it can take a bit and so long as you don't click anything it should reliably hibernate every time. If it won't reliably do that let me know as there could be another issue. 

Anyway, expect another good update soon as I have a few more optimizations and fixes coming.

**Comment by Nyryzu** [comment]
cool ! I am expecting good stuff as usual as for the sleep/hibernate function is unfortunate as it is and it's driving me crazy but I just have to get used to it.

I also wanted to to ask: 

1) how can I use the full internal resolution of the display without having the UI look so eye piercingly small ? I am currently on 1600x1066, it gives me good quality with decent battery life. 

2) Speaking of battery life, what is the most you got so far on a full charge ? Just comparing for fun. Mine is around 3 hours

3) I understand internal WIFI wont ever work but I saw you talking in another thread that Bluetooth might work just like it did on some older SP models, is there any hope for SP3 ?

**Comment by balopez83** [comment]
@Nyryzu so for your first question; you have the right idea on the screen resolution. There is a way to enable HiDPI however I have never been successful in actually having it work on the SP3. I also use the 1600x1066 and it seems to be close enough to where HiDPI would have gotten it. 

2) Battery life is a good question; I believe I have seen upwards of 4 hours but not recently. In the 5.2.0 release I added a corrected power management SSDT that manages the CPU a little better. Unfortunately, I accidentally omitted it in the last few releases and I believe it reduced the overall battery life. 

3) I don't have hi hopes for built in bluetooth honestly. I need to get access to the source code for the AvastarFWLoader.kext or Avastar.kext but the author Jape has since pulled it down and I have been unable to make contact. If I had the source code I believe I could modify it to make it work. I have tried making the kexts attach modifying the config within the kexts but the code has to be changed within the kext code and I can only do that with the source code. 

I am going to close this issue as resolved now. I am confident everything should be resolved in the 5.2.0 release [coming within the hour]. If you notice something is still wrong start another issue and let me know.

**Comment by Xryphon** [comment]
Hi,

Really sorry to be posting on a closed thread, but I have been experiencing issues with various applications such as Firefox and Authy, and it seems to be related to the graphics like you have stated.

I'm on macOS 13.5 and Firefox will load but then essentially hang and sometimes crashes when opening a tab. Authy refuses to open at all, and crashes.

**Comment by balopez83** [comment]
Hi @Xryphon Unfortunately Firefox seems to be really buggy on the SP3 from Monterey on. You can try the config for the i7 SP3 or try the dev versions of Firefox and see if that fixes it for you as it has for some users.

Unfortunately there isn't anything that I believe can be done to fix those issues as the SP3 hardware hasnt been officially supported since Big Sur. Ventura is using patched graphics which introduces other variables that makes it harder to fix as well. 

I will look into those issues but I dont believe they will be easily resolved.
